name: JHipster Workflow

on:
  push:
    branches: [ main ]

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
          
      - name: Install JHipster
        run: npm install -g generator-jhipster

      - name: Generate code
        run: |
          # Replace 'jhipster-jdl-file.jdl' with the actual JDL file name
          jhipster import-jdl TESTFILE.jdl

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS EKS
        run: |
          # Replace 'your-eks-cluster-name' with the actual EKS cluster name
          aws eks update-kubeconfig --region ap-south-1 --name vaidhyamegha-eks
          kubectl apply -f deployment.yml

      - name: Deploy RDS PostgreSQL
        run: |
          # Replace 'your-postgresql-configuration' with the actual PostgreSQL configuration
          aws rds --region ap-south-1 create-db-instance --db-instance-identifier test-jh-eks3 --engine postgres --allocated-storage 20 --db-instance-class DB.m5d.large --master-username master --master-user-password password

      - name: Deploy Amazon OpenSearch Service
        run: |
          # Replace 'your-opensearch-configuration' with the actual OpenSearch domain configuration
          aws opensearch create-domain 	jhipster-eks your-opensearch-configuration --version 1.0
      - name: Commit and push if it's not a pull request
        run: |
          git config --local user.email "sai@vaidhyamegha.com"
          git config --local user.name "saichandyadavalli"
          git add -A
          git commit -m "Add changes from JHipster generation" -a
          git push
